### ISSUE TITLE
Multi-Label Or Multi-Class???

### ISSUE THREAD

**Issue by RishitJoshi97** [tasrif-khondaker/HD-CapsNet#2]
Thank you for this awesome work. 
# Question on HD-CapsNet Implementation for Multi-label Hierarchical Classification

## Current Implementation Status
I am currently working with your HD-CapsNet implementation, specifically using the `HD_CapsNet.ipynb` file from the CIFAR-10 folder as my starting point for a hierarchical classification task.

## Dataset Clarification
I noticed something that needs clarification:
1. Your paper discusses multi-label classification, but the datasets used (CIFAR-10, MNIST, Fashion-MNIST) are traditionally multi-class datasets where each image has exactly one class label.
2. Could you clarify if the implementation was designed for multi-class, multi-label, or both scenarios?

## My Use Case
I'm working on a hierarchical image classification problem with these characteristics:
- Three hierarchical levels: main_category → sub_category → fine_category
- Multi-label at each level (single image can have multiple categories)

Would the following components need modification:
   - Model architecture
   - Loss function 
   -Metrics 
   - Output layer structure
   - Training procedure

3. Is there anything specific I should be careful about when adapting the CIFAR-10 implementation for my multi-label scenario?

i am new to this work so any guidance would be greatly appreciated as I work to adapt your implementation for my use case.

Example from my dataset:(does not represent class just for explanation)
main_category: 25, (Animal),26(Transport)
└── sub_category: 2505 (Mammal),2605(Sky)
└── fine_category: 250501 (Whale),260501(Airplane)
![image](https://github.com/user-attachments/assets/04a752ec-437e-4c61-ae50-62b3886e1bae)

**Comment by tasrif-khondaker** [comment]
Thank you for your interest in our work and for raising these insightful questions regarding the implementation of HD-CapsNet for hierarchical classification.  

To clarify, the current implementation of HD-CapsNet, as discussed in our paper and exemplified in the provided code, is indeed designed for **hierarchical multi-label classification problems**. Specifically:  

- **Hierarchical Structure:** The model is well-suited for scenarios where each sample can belong to multiple labels across a hierarchical taxonomy. For example, an image might belong to multiple categories at the `main_category` level (e.g., Animal and Transport) and further have subcategories and fine-grained labels under each parent category.  
- **Multi-Label Design:** At each hierarchical level, a single image can be associated with multiple labels, and each label can encompass multiple classes.

## Addressing Your Specific Questions  

1. **Dataset Use in Implementation:**  
   While datasets like CIFAR-10, MNIST, and Fashion-MNIST are traditionally multi-class, in our implementation, we have used hierarchical versions of these datasets to align with the hierarchical multi-label classification framework. For instance, the CIFAR-10 dataset has been organised into a hierarchical taxonomy as follows:  

   ```
   Root
   ├── animal -> (L0_1)
   │   ├── bird -> (L1_3)
   │   │   └── bird -> (L2_2)
   │   ├── medium -> (L1_6)
   │   │   ├── deer -> (L2_4)
   │   │   └── horse -> (L2_7)
   │   ├── pet -> (L1_5)
   │   │   ├── cat -> (L2_3)
   │   │   └── dog -> (L2_5)
   │   └── reptile -> (L1_4)
   │       └── frog -> (L2_6)
   └── transport -> (L0_0)
       ├── road -> (L1_2)
       │   ├── automobile -> (L2_1)
       │   └── truck -> (L2_9)
       ├── sky -> (L1_0)
       │   └── airplane -> (L2_0)
       └── water -> (L1_1)
           └── ship -> (L2_8)
   ```

   This hierarchical structure allows the model to learn relationships across levels (e.g., `animal → bird → bird` or `transport → road → truck`) while also handling the multi-label nature of the classification task. Further details about this hierarchical adaptation are provided in the code for reference.  

   The model is capable of extension to more complex hierarchical multi-label datasets, like the one you described, using similar principles.  

2. **Adapting to Your Use Case:**  
   Given your dataset with three hierarchical levels (`main_category`, `sub_category`, `fine_category`) and multi-label characteristics, the following components might require adaptation:  

   - **Model Architecture:**  
     Ensure that the architecture accommodates the taxonomy structure of your dataset. The capsule layers should be adjusted to represent the hierarchy, with appropriate routing mechanisms for parent and child relationships.

   - **Training Procedure:**  
     Pay attention to how hierarchical relationships are handled during training. For instance, imposing constraints to ensure consistency between parent and child labels could enhance performance.  

## Additional Considerations  

When adapting the CIFAR-10 implementation for your multi-label use case, here are some points to keep in mind:  

- Carefully define the taxonomy matrix for your dataset to capture the hierarchical relationships.  
- Ensure that the data preprocessing pipeline supports multiple labels per sample.  
- Visualise and monitor hierarchical saliency or activation maps at each level to verify that the model learns meaningful features.  

Feel free to share specific challenges or aspects of your implementation where you need further clarification. We are happy to provide more guidance as you adapt HD-CapsNet for your hierarchical multi-label classification task.
